@startuml
skinparam classAttributeIconSize 0

' --- Интерфейс Helper ---
interface Helper {
    + предоставитьУбежище(): Boolean
    + датьПодсказку(): String
}

' --- Реализации Helper ---
class Яблоня implements Helper {
    + продукт = "Яблоко"
    + съедено = false
    + съестьПродукт()
    + предоставитьУбежище()
    + датьПодсказку()
}

class Печка implements Helper {
    + продукт = "Пирожок"
    + съедено = false
    + съестьПродукт()
    + предоставитьУбежище()
    + датьПодсказку()
}

class Речка implements Helper {
    + продукт = "Кисель"
    + съедено = false
    + съестьПродукт()
    + предоставитьУбежище()
    + датьПодсказку()
}

' --- Иерархия персонажей ---
class Девочка {
    + голод: int = 100
    + братНайден = false
    + спрятана = false
    + съестьПродукт(объект: Helper)
    + спроситьПодсказку(объект: Helper)
    + найтиБрата()
}

class ГусиЛебеди {
    + скорость = 50
    + погоняАктивна = true
    + лететь()
    + схватитьБрата()
}

class Братец {
    + состояние: String = "похищен"
    + ждатьСпасения()
}

' СВЯЗИ
Девочка ..> Helper : <<use>>
ГусиЛебеди --> Братец : преследует >
Helper "0..1" -- "1" Девочка : укрывает >

note right of Helper::предоставитьУбежище
  **Conditional Strategy**
  if (съедено == true)
    return true (укрыть)
  else
    return false (не помогать)
end note

note bottom of Девочка
  Девочка должна съесть продукт,
  чтобы объект помог ей
  спрятаться от гусей.
end note

@enduml
